apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - mysql-deployment.yaml
  - mysql-configmap.yaml
  - mysql-service.yaml
  - mysql-secret.yaml
  - mysql-longhorn-pvc.yaml