apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: project

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0

          ports:
            - containerPort: 3306

          envFrom:
            - configMapRef:
                name: mysql-configmap

            - secretRef:
                name: mysql-secret

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-longhorn-pvc
