apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- ../../base
- ingress.yaml
images:
- name: gyueon/testconsumer
  newName: gyueon/testconsumer
  newTag: sha-b25b6c067fdbf4708a37d4876cbc0baee84d87de
- name: gyueon/testproducer
  newName: gyueon/testproducer
  newTag: sha-056897c955387c2e02ab590a8e12f9d839a5a41c
