apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- ../../base
- ingress.yaml
images:
- name: gyueon/testconsumer
  newName: gyueon/testconsumer
  newTag: sha-056897c955387c2e02ab590a8e12f9d839a5a41c
- name: gyueon/testproducer
  newName: gyueon/testproducer
  newTag: sha-138bd367e7ada97f2eaf014b58dc2c33c478f890
